"""Daily GitHub snapshot — the repo's visible proof the pipeline ran today.

The database is local-only; GitHub never sees it. This script exports a
small, licence-clean slice to snapshots/, which truckintel-git-push commits
and pushes every day:

  diesel_prices_eia.csv   EIA weekly diesel by region — US public domain,
                          the ONLY fuel series that may appear in a PUBLIC
                          repo. AAA daily is personal-use-only (see
                          deploy/truckintel-aaa-prices.service), so it shows
                          up in summary.md as metadata (last date, state
                          count) and never as prices.
  summary.md              per-layer row counts (mechanics, truck routes,
                          repair POIs, businesses) + per-source freshness.

Small by design: the full tables live in Postgres; the snapshot is the
heartbeat. Idempotent — rerunning on the same data produces byte-identical
files, so the git-push job commits nothing on a day with no changes.
"""
from __future__ import annotations

import csv
from pathlib import Path

from truckintel.db import fetch_all, fetch_one

SNAP_DIR = Path(__file__).resolve().parents[1] / "snapshots"

# Same statuses freshness_check.py counts as alive: re-verified-unchanged
# data is fresh data.
FRESH_STATUSES = ["success", "skipped_unchanged"]

COUNT_TABLES = [
    ("Truck routes (NTAD national network)", "core.truck_routes"),
    ("Mechanic shops", "core.mechanic_shops"),
    ("Truck-repair POIs (OSM)", "osm.truck_repair"),
    ("Fuel stations (OSM)", "osm.fuel_stations"),
    ("Businesses (conflated)", "core.businesses"),
]


def export_eia_csv() -> int:
    rows = fetch_all(
        "SELECT region, product, week_of, price_usd_gal"
        " FROM core.fuel_prices"
        " WHERE week_of >= (SELECT max(week_of) FROM core.fuel_prices)"
        "                  - INTERVAL '84 days'"
        " ORDER BY week_of DESC, region"
    )
    with open(SNAP_DIR / "diesel_prices_eia.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["region", "product", "week_of", "price_usd_gal"])
        for region, product, week_of, price in rows:
            w.writerow([region, product, week_of.isoformat(), price])
    return len(rows)


def main() -> None:
    SNAP_DIR.mkdir(exist_ok=True)
    eia_rows = export_eia_csv()

    aaa = fetch_one(
        "SELECT max(observed_on), count(DISTINCT state)"
        " FROM core.fuel_prices_daily WHERE source_id = 'aaa_daily'"
    )
    aaa_date, aaa_states = (aaa or (None, 0))

    counts = []
    for label, table in COUNT_TABLES:
        row = fetch_one(f"SELECT count(*) FROM {table}")  # noqa: S608 — fixed list above
        counts.append((label, table, row[0] if row else 0))

    fresh = fetch_all(
        "SELECT source_id, now() - max(coalesce(finished_at, started_at))"
        " FROM ops.source_runs WHERE status = ANY(%s)"
        " GROUP BY source_id ORDER BY source_id",
        (FRESH_STATUSES,),
    )

    # snapshot_date deliberately comes from the DATA (max EIA week / AAA day
    # is in the tables), not from now(): the file must be reproducible.
    lines = [
        "# truck-intel daily snapshot",
        "",
        "Auto-generated by `scripts/daily_snapshot.py`; committed daily by",
        "the `truckintel-git-push` timer. The full dataset lives in a local",
        "PostGIS database — this file is the heartbeat.",
        "",
        "## Fuel",
        "",
        f"- EIA weekly diesel (public domain): {eia_rows} rows,"
        " last 12 weeks → [diesel_prices_eia.csv](diesel_prices_eia.csv)",
        f"- AAA daily state diesel (personal-use licence — prices NOT"
        f" republished): last pull {aaa_date}, {aaa_states} states",
        "",
        "## Layers",
        "",
        "| layer | table | rows |",
        "|---|---|---:|",
    ]
    lines += [f"| {label} | `{table}` | {n:,} |" for label, table, n in counts]
    lines += [
        "",
        "## Source freshness (age of last successful run)",
        "",
        "| source | age |",
        "|---|---|",
    ]
    # Hours, floored — minutes would make the file churn on every rerun.
    for source_id, age in fresh:
        hours = int(age.total_seconds() // 3600)
        lines.append(f"| {source_id} | {hours}h |")
    lines.append("")

    (SNAP_DIR / "summary.md").write_text("\n".join(lines))
    print(f"[snapshot] {eia_rows} EIA rows, {len(counts)} layers, "
          f"{len(fresh)} sources → {SNAP_DIR}")


if __name__ == "__main__":
    main()
