"""Mapbox Vector Tiles for the local data viewer.

One endpoint, one layer registry. Every layer is a real core/osm table — the
tile is generated by PostGIS (`ST_AsMVT`), so 450k route rows render without
the API ever materialising them as JSON.

Two rules this file inherits from the rest of the API:
- read-only session (`common.connect_ro`), so a viewer can never mutate data;
- the route network is the *truck-designated* network only (`core.truck_routes`,
  NTAD National Network). `osm.ways` is deliberately NOT a layer here: it is the
  generic road graph and must never be shown as a truck route.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import psycopg
from fastapi import APIRouter, Path
from fastapi.responses import Response

from api import common

router = APIRouter(tags=["viewer"])

MVT_EXTENT = 4096
MVT_BUFFER = 64
# ST_TileEnvelope margin, in tile fractions: pull in features just outside the
# tile so lines and symbols do not get clipped at the seam.
TILE_MARGIN = 0.0625
# Density-grid resolution at low zoom: cells across one tile edge. 64 => at most
# 4,096 features per tile regardless of how many rows fall inside it.
CLUSTER_CELLS = 64
# Below this zoom, point layers are drawn as a density grid instead of as
# individual rows. Above it, every row in view is drawn.
POINT_CLUSTER_ZOOM = 8

# Gate 6 (truckintel.liveness) on the map: keep a place off the map only when a
# source POSITIVELY asserted it closed. Deliberately NOT `liveness >= n`:
#
#   'closed'         a source said so         -> hide. This is an assertion.
#   'likely_closed'  scored under 25          -> SHOW, badged. This is a score.
#   'unknown'        old data, nothing current-> SHOW, badged.
#   NULL             never scored             -> SHOW. Unscored is not closed,
#                                               and IS DISTINCT FROM keeps it.
#
# Hiding low scores would turn "nobody has confirmed this since 2019" into
# "this is gone", which is the inference liveness.py exists to refuse. The
# driver at 2 a.m. is better served by a badged maybe than by an empty map.
LIVE_FILTER = "live_state IS DISTINCT FROM 'closed'"


@dataclass(frozen=True)
class Layer:
    """One map layer: where it lives, what a click should show, how dense it is."""

    table: str
    id_col: str
    props: tuple[str, ...]
    kind: str  # "line" | "point" — drives the viewer's style
    min_zoom: int  # below this, the viewer does not request tiles at all
    max_features: int  # per-tile guard; the viewer reports when it bites
    label: str
    color: str
    order_by: str | None = None  # optional: which rows survive the LIMIT first
    # Optional SQL predicate that decides which rows are ON the map at all, e.g.
    # "on_route_5km". A filtered layer is a DIFFERENT count from its table, so
    # /v1/viewer/inventory reports rows_mapped AND rows_total side by side —
    # a map showing fewer dots than the table holds must always be visible as a
    # number, never discovered by eye.
    row_filter: str | None = None
    # Generalized stand-in used below `gen_below_zoom`, so a low-zoom tile shows
    # the WHOLE layer at lower detail instead of a LIMIT-truncated slice of it.
    gen_table: str | None = None
    gen_below_zoom: int = 0
    # Point layers below this zoom are served as a density grid (one feature per
    # cell, carrying `n`). Every row is still counted — nothing is dropped, the
    # unit of display just changes from "a station" to "how many stations here".
    cluster_below_zoom: int = 0
    # Drawn on first load? The dense layers start off: 629k bridge markers on top
    # of everything else is not "seeing your data", it is hiding it. One click on.
    default_on: bool = True
    flags: tuple[str, ...] = field(default=())

    def source_for(self, z: int) -> tuple[str, bool]:
        """(table, is_generalized) for this zoom."""
        if self.gen_table and z < self.gen_below_zoom:
            return self.gen_table, True
        return self.table, False

    def clustered_at(self, z: int) -> bool:
        return self.kind == "point" and z < self.cluster_below_zoom


LAYERS: dict[str, Layer] = {
    "truck_routes": Layer(
        table="core.truck_routes",
        id_col="route_id",
        props=(
            "route_name",
            "route_ref",
            "sign_type",
            "sign_num",
            "state",
            "fclass",
            "aadt",
            "aadt_com",
            "through_lanes",
        ),
        kind="line",
        min_zoom=3,
        max_features=25000,
        label="Truck routes",
        color="#f59e0b",
        # Busiest first, so a capped tile still shows the important corridors.
        order_by="aadt_com DESC NULLS LAST",
        # A z4 tile covers ~110k raw segments against a 12k cap — that would be a
        # silent 90% drop. Below z8 we serve the dissolved corridors instead:
        # 3,282 rows, 99.4% of the network mileage, zero truncation.
        gen_table="core.truck_routes_gen",
        gen_below_zoom=9,
    ),
    "fuel_stations": Layer(
        table="osm.fuel_stations",
        id_col="osm_id",
        props=("name", "brand", "state", "has_diesel", "hgv_access", "has_def",
               "route_ref", "route_dist_m", "verification_status"),
        kind="point",
        min_zoom=3,
        max_features=25000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        label="Fuel stations",
        color="#22c55e",
        # On the truck network only, plus the two *known* negatives. Diesel is
        # untagged on 93% of OSM rows, so requiring has_diesel = true would drop
        # the layer to a metadata artifact; `IS NOT FALSE` keeps untagged rows
        # (displayed as "unknown") and drops only pumps explicitly tagged as
        # having no diesel or as barring HGVs. See scripts/fuel_routes.py.
        row_filter=(
            "on_route_5km AND hgv_access IS NOT FALSE AND has_diesel IS NOT FALSE"
        ),
    ),
    "bridges": Layer(
        table="core.bridges",
        id_col="nbi_id",
        props=(
            "name",
            "state",
            "min_vert_clearance_in",
            "posting_status",
            "operating_rating",
            "inventory_rating",
        ),
        kind="point",
        min_zoom=3,
        max_features=25000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        default_on=False,
        label="Bridges",
        color="#60a5fa",
    ),
    "parking_sites": Layer(
        table="core.parking_sites",
        id_col="site_id",
        props=("name", "kind", "state", "truck_spaces", "live_state", "liveness"),
        kind="point",
        min_zoom=3,
        max_features=4000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        label="Truck parking",
        color="#06b6d4",
        # Gate 6. Only a POSITIVE closure assertion is dropped — see the note
        # on mechanic_shops below. Most of this layer scores 'unknown' (2019
        # Jason's Law vintage, nothing current); 'unknown' stays on the map
        # with its badge, because hiding it would be inferring closure.
        row_filter=LIVE_FILTER,
    ),
    "rest_areas": Layer(
        table="osm.rest_areas",
        id_col="osm_id",
        props=("name", "state"),
        kind="point",
        min_zoom=3,
        max_features=6000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        default_on=False,
        label="Rest areas",
        color="#a78bfa",
    ),
    "weigh_points": Layer(
        table="osm.weigh_points",
        id_col="osm_id",
        props=("name", "state"),
        kind="point",
        min_zoom=3,
        max_features=6000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        default_on=False,
        label="Weigh stations",
        color="#ef4444",
    ),
    "tunnels": Layer(
        table="core.tunnels",
        id_col="tunnel_id",
        props=(
            "name",
            "state",
            "length_ft",
            "min_vert_clearance_in",
            "hazmat_restricted",
        ),
        kind="point",
        min_zoom=3,
        max_features=2000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        label="Tunnels",
        color="#f472b6",
    ),
    # core.businesses is deliberately NOT a map layer (removed 2026-07-26).
    #
    # It held 2,981 general POI — 1,093 restaurants, 628 cafes, 362 ATMs, 265
    # grocery, 220 hotels — against exactly 1 truck_repair row, and the viewer's
    # "Mechanics" toggle was aliased to it as a stand-in. So the orange dots on
    # screen were 99.7% not mechanics. This is a truck map: the service layers
    # are fuel and truck mechanics, and restaurant/cafe/ATM noise does not help
    # anyone move a 40-tonne vehicle.
    #
    # The table and its monthly pipeline are untouched — nothing was deleted, so
    # restoring the layer is a matter of putting this entry back.
    "mechanic_shops": Layer(
        table="core.mechanic_shops",
        id_col="shop_id",
        props=(
            "name",
            "category",
            "city",
            "state",
            "phone",
            "website",
            "route_ref",
            "route_dist_m",
            "verification_status",
            "confidence",
            "gmaps_url",
            "live_state",
            "liveness",
        ),
        kind="point",
        min_zoom=3,
        # 11,759 rows nationally; a z9 tile over Dallas holds a few hundred, so
        # the cap never bites. Sized against the whole layer, not a guess.
        max_features=12000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        # Best-verified shops survive first if a dense tile ever does hit the cap.
        order_by="confidence DESC NULLS LAST",
        default_on=False,
        label="Truck mechanics",
        color="#fb923c",
        # Same 5 km truck-route buffer as the fuel layer and as corridor.py's
        # service_buffer_m: a shop a driver cannot reach from the network is not
        # a shop this map should promise. 9,809 of 11,759 qualify.
        #
        # Gate 6 rides along on the same predicate: a shop a source positively
        # says is CLOSED is not a shop this map should promise either. Boss,
        # 2026-08-17: "mechanic ki shop close hui vo nhi dikhani chiye hame."
        row_filter=f"on_route_5km AND {LIVE_FILTER}",
    ),
    "live_events": Layer(
        table="core.live_events",
        id_col="event_id",
        props=("kind", "source_id", "first_seen", "last_seen"),
        kind="point",
        min_zoom=3,
        max_features=6000,
        cluster_below_zoom=POINT_CLUSTER_ZOOM,
        default_on=False,
        label="Live events",
        color="#fb923c",
    ),
}


# Columns the generalized route table does not carry. They stay in the tile
# schema as NULL so a popup renders them as "unknown" rather than vanishing.
_GEN_ABSENT: dict[str, frozenset[str]] = {
    "core.truck_routes_gen": frozenset({"fclass", "through_lanes"}),
}

# A generalized stand-in table is a different table, and there is no guarantee it
# carries the filter column. Silently dropping the predicate at low zoom would
# show rows the layer promises to exclude, so the combination is banned outright
# rather than special-cased.
for _name, _spec in LAYERS.items():
    if _spec.row_filter and _spec.gen_table:
        raise AssertionError(
            f"layer '{_name}' sets both row_filter and gen_table; the filter "
            f"would be unenforceable below zoom {_spec.gen_below_zoom}"
        )


def _filter_clause(layer: Layer, alias: str = "t") -> str:
    """`AND <predicate>` for a filtered layer, or '' — safe to concatenate.

    The predicate is developer-authored code in this module's registry, never
    request input, so it is interpolated rather than parameterised. Column
    references are alias-qualified so the clause is valid in either query shape.
    """
    if not layer.row_filter:
        return ""
    return f" AND {alias}.{layer.row_filter}"


def _cluster_sql(layer: Layer, z: int) -> str:
    """Density grid for a point layer at low zoom.

    Rows are snapped to a grid whose cell is 1/CLUSTER_CELLS of the tile, so a
    tile carries at most CLUSTER_CELLS^2 features no matter how dense the data
    is — bounded work, and `n` accounts for every row in the cell.
    """
    return f"""
        WITH b AS (
            SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS tile,
                   ST_Transform(
                       ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => {TILE_MARGIN}),
                       4326
                   ) AS lookup
        ),
        cells AS (
            -- Grouped BY the grid, but placed at the mean position of the rows in
            -- the cell. Snapping the marker to the grid instead draws a visible
            -- lattice across the country — an artifact of the cell size, not of
            -- where anything actually is.
            SELECT ST_Centroid(ST_Collect(t.geom)) AS cell, count(*)::int AS n
            FROM {layer.table} t, b
            WHERE t.geom && b.lookup{_filter_clause(layer)}
            GROUP BY ST_SnapToGrid(t.geom, %(cell)s)
        ),
        mvt AS (
            SELECT ST_AsMVTGeom(
                       ST_Transform(cells.cell, 3857), b.tile,
                       {MVT_EXTENT}, {MVT_BUFFER}, true
                   ) AS geom,
                   cells.n
            FROM cells, b
        )
        SELECT ST_AsMVT(mvt, %(layer)s, {MVT_EXTENT}, 'geom') AS tile FROM mvt
    """


def _tile_sql(layer: Layer, z: int) -> str:
    """MVT for one tile.

    The bbox filter runs against the stored 4326 geometry so the GIST index is
    usable; only the surviving rows are reprojected to 3857 for ST_AsMVTGeom.
    """
    table, generalized = layer.source_for(z)
    absent = _GEN_ABSENT.get(table, frozenset())
    prop_cols = ", ".join(
        f"NULL AS {c}" if c in absent else f"t.{c}" for c in layer.props
    )
    order_by = layer.order_by
    if order_by and order_by.split()[0] in absent:
        order_by = None
    order_clause = f"ORDER BY t.{order_by}" if order_by else ""
    return f"""
        WITH b AS (
            SELECT ST_TileEnvelope(%(z)s, %(x)s, %(y)s) AS tile,
                   ST_Transform(
                       ST_TileEnvelope(%(z)s, %(x)s, %(y)s, margin => {TILE_MARGIN}),
                       4326
                   ) AS lookup
        ),
        src AS (
            SELECT t.{layer.id_col}::text AS feature_id, {prop_cols}, t.geom
            FROM {table} t, b
            WHERE t.geom && b.lookup{_filter_clause(layer)}
            {order_clause}
            LIMIT %(limit)s
        ),
        mvt AS (
            SELECT ST_AsMVTGeom(
                       ST_Transform(src.geom, 3857), b.tile,
                       {MVT_EXTENT}, {MVT_BUFFER}, true
                   ) AS geom,
                   src.feature_id, {", ".join(f"src.{c}" for c in layer.props)}
            FROM src, b
        )
        SELECT ST_AsMVT(mvt, %(layer)s, {MVT_EXTENT}, 'geom') AS tile FROM mvt
    """


@router.get("/v1/tiles/{layer}/{z}/{x}/{y}.mvt")
def tile(
    layer: str,
    z: int = Path(ge=0, le=22),
    x: int = Path(ge=0),
    y: int = Path(ge=0),
) -> Response:
    """One vector tile. 204 when the tile is empty — MapLibre treats it as blank."""
    spec = LAYERS.get(layer)
    if spec is None:
        raise common.ApiError(
            "not_found",
            f"unknown layer '{layer}'; known: {', '.join(sorted(LAYERS))}",
            status=404,
        )
    span = 1 << z
    if x >= span or y >= span:
        raise common.ApiError("invalid_param", f"x/y out of range for zoom {z}")

    table, generalized = spec.source_for(z)
    clustered = spec.clustered_at(z)
    params = {"z": z, "x": x, "y": y, "limit": spec.max_features, "layer": layer}
    if clustered:
        # Tile spans 360/2^z degrees of longitude; CLUSTER_CELLS cells across it.
        params["cell"] = (360.0 / (1 << z)) / CLUSTER_CELLS
        sql = _cluster_sql(spec, z)
    else:
        sql = _tile_sql(spec, z)

    try:
        with common.connect_ro() as conn:
            row = conn.execute(sql, params).fetchone()
    except psycopg.Error as exc:
        raise common.ApiError(
            "upstream_unavailable",
            f"database unavailable ({type(exc).__name__})",
            status=503,
        ) from exc

    blob = bytes(row["tile"]) if row and row["tile"] is not None else b""
    if not blob:
        return Response(status_code=204)
    return Response(
        content=blob,
        media_type="application/vnd.mapbox-vector-tile",
        headers={
            "Cache-Control": "public, max-age=300",
            # Which table this tile actually came from — so "what am I looking at"
            # is answerable from the wire, not from reading this file.
            "X-Source-Table": table,
            "X-Generalized": "true" if generalized else "false",
            "X-Clustered": "true" if clustered else "false",
        },
    )


@router.get("/v1/tiles")
def tile_layers() -> dict:
    """The layer registry the viewer builds its legend and sources from."""
    return {
        "extent": MVT_EXTENT,
        "layers": [
            {
                "id": name,
                "label": spec.label,
                "kind": spec.kind,
                "color": spec.color,
                "table": spec.table,
                "min_zoom": spec.min_zoom,
                "max_features_per_tile": spec.max_features,
                "generalized_below_zoom": spec.gen_below_zoom or None,
                "generalized_table": spec.gen_table,
                "cluster_below_zoom": spec.cluster_below_zoom or None,
                "default_on": spec.default_on,
                "props": list(spec.props),
            }
            for name, spec in LAYERS.items()
        ],
    }
